import{randomUUID}from'node:crypto';import{Injectable}from'@nestjs/common';import type{ReferenceDataUpsertRequest}from'@health/contracts';import{DatabaseService}from'../../database/database.service.js';
@Injectable()export class ReferenceDataService{constructor(private readonly db:DatabaseService){}
 list(kind:'provinces'|'specialties'|'nursing-services'){const sql=kind==='provinces'?`SELECT id,name_ar AS "nameAr",name_en AS "nameEn",is_active AS "isActive",sort_order AS "sortOrder" FROM provinces ORDER BY sort_order`:kind==='specialties'?`SELECT id,name_ar AS "nameAr",name_en AS "nameEn",is_active AS "isActive",sort_order AS "sortOrder" FROM doctor_specialties ORDER BY sort_order`:`SELECT id,name_ar AS "nameAr",name_en AS "nameEn",is_active AS "isActive",sort_order AS "sortOrder" FROM nursing_services ORDER BY sort_order`;return this.db.query(sql).then(r=>r.rows)}
 async listActive(kind:'specialties'|'nursing-services'){const table=kind==='specialties'?'doctor_specialties':'nursing_services';return(await this.db.query(`SELECT id,name_ar AS "nameAr",name_en AS "nameEn" FROM ${table} WHERE is_active=TRUE ORDER BY sort_order,name_ar`)).rows}
 async update(kind:'provinces'|'specialties'|'nursing-services',id:string,input:ReferenceDataUpsertRequest){const table=kind==='provinces'?'provinces':kind==='specialties'?'doctor_specialties':'nursing_services';await this.db.query(`UPDATE ${table} SET name_ar=$2,name_en=$3,is_active=$4,sort_order=$5 WHERE id=$1`,[id,input.nameAr,input.nameEn??null,input.isActive,input.sortOrder]);return{ok:true as const}}
 async listCities(provinceId:string){return(await this.db.query(`SELECT id,province_id AS "provinceId",name_ar AS "nameAr",name_en AS "nameEn",is_active AS "isActive",sort_order AS "sortOrder" FROM cities WHERE province_id=$1 ORDER BY sort_order`,[provinceId])).rows}
 async upsertCity(id:string|undefined,provinceId:string,input:ReferenceDataUpsertRequest){const cityId=id??randomUUID();await this.db.query(`INSERT INTO cities(id,province_id,name_ar,name_en,is_active,sort_order) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET name_ar=EXCLUDED.name_ar,name_en=EXCLUDED.name_en,is_active=EXCLUDED.is_active,sort_order=EXCLUDED.sort_order`,[cityId,provinceId,input.nameAr,input.nameEn??null,input.isActive,input.sortOrder]);return{id:cityId}}
 async listNeighborhoods(cityId:string){return(await this.db.query(`SELECT id,city_id AS "cityId",name_ar AS "nameAr",name_en AS "nameEn",is_active AS "isActive",sort_order AS "sortOrder" FROM neighborhoods WHERE city_id=$1 ORDER BY sort_order`,[cityId])).rows}
 async upsertNeighborhood(id:string|undefined,cityId:string,input:ReferenceDataUpsertRequest){const neighborhoodId=id??randomUUID();await this.db.query(`INSERT INTO neighborhoods(id,city_id,name_ar,name_en,is_active,sort_order) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO UPDATE SET name_ar=EXCLUDED.name_ar,name_en=EXCLUDED.name_en,is_active=EXCLUDED.is_active,sort_order=EXCLUDED.sort_order`,[neighborhoodId,cityId,input.nameAr,input.nameEn??null,input.isActive,input.sortOrder]);return{id:neighborhoodId}}
 async create(kind:'specialties'|'nursing-services',input:ReferenceDataUpsertRequest){const id=randomUUID(),table=kind==='specialties'?'doctor_specialties':'nursing_services';await this.db.query(`INSERT INTO ${table}(id,name_ar,name_en,is_active,sort_order) VALUES($1,$2,$3,$4,$5)`,[id,input.nameAr,input.nameEn??null,input.isActive,input.sortOrder]);return{id}}
}
