import{Controller,Get,Param,Query}from'@nestjs/common';import{facilityDiscoveryQuerySchema,mapBoundsQuerySchema,parseCoordinates,parseIdentifier,issue,searchQuerySchema}from'@health/contracts';import{PublicDiscoveryService}from'./public-discovery.service.js';
function coords(q:Record<string,string|undefined>){const hasLat=q.latitude!==undefined,hasLon=q.longitude!==undefined;if(!hasLat&&!hasLon)return undefined;if(!hasLat||!hasLon)issue('$.coordinates','latitude and longitude must be provided together');return parseCoordinates({latitude:Number(q.latitude),longitude:Number(q.longitude)},'$.coordinates')}
@Controller()export class PublicDiscoveryController{constructor(private readonly discovery:PublicDiscoveryService){}
@Get('directory/facilities')list(@Query()q:Record<string,string|undefined>){const input=facilityDiscoveryQuerySchema.parse({provinceId:q.provinceId,categoryId:q.categoryId,coordinates:coords(q),...(q.cityId?{cityId:q.cityId}:{}),...(q.specialtyId?{specialtyId:q.specialtyId}:{}),...(q.nursingServiceId?{nursingServiceId:q.nursingServiceId}:{}),...(q.openNow!==undefined?{openNow:q.openNow==='true'}:{}),...(q.dutyNow!==undefined?{dutyNow:q.dutyNow==='true'}:{}),...(q.page?{page:Number(q.page)}:{}),...(q.pageSize?{pageSize:Number(q.pageSize)}:{})});return this.discovery.discover(input)}
@Get('directory/facilities/:id')detail(@Param('id')id:string){return this.discovery.detail(parseIdentifier(id,'$.id'))}
@Get('directory/search')search(@Query()q:Record<string,string|undefined>){return this.discovery.search(searchQuerySchema.parse({query:q.q,provinceId:q.provinceId,coordinates:coords(q),...(q.categoryId?{categoryId:q.categoryId}:{}),...(q.specialtyId?{specialtyId:q.specialtyId}:{}),...(q.nursingServiceId?{nursingServiceId:q.nursingServiceId}:{}),...(q.openNow!==undefined?{openNow:q.openNow==='true'}:{}),...(q.dutyNow!==undefined?{dutyNow:q.dutyNow==='true'}:{}),...(q.page?{page:Number(q.page)}:{}),...(q.pageSize?{pageSize:Number(q.pageSize)}:{})}))}
@Get('directory/map')map(@Query()q:Record<string,string|undefined>){const input=mapBoundsQuerySchema.parse({north:Number(q.north),south:Number(q.south),east:Number(q.east),west:Number(q.west),provinceId:q.provinceId,...(q.categoryId?{categoryId:q.categoryId}:{}),...(q.openNow!==undefined?{openNow:q.openNow==='true'}:{}),...(q.dutyNow!==undefined?{dutyNow:q.dutyNow==='true'}:{})});return this.discovery.map(input)}
@Get('home')home(@Query()q:Record<string,string|undefined>){return this.discovery.home({provinceId:parseIdentifier(q.provinceId,'$.provinceId'),...(coords(q)?{coordinates:coords(q)!}:{})})}
}
