import React,{useCallback,useEffect,useState}from'react';import{ScrollView,StyleSheet}from'react-native';import type{NativeStackScreenProps}from'@react-navigation/native-stack';import type{DirectoryCategoryDTO,FacilityListDTO}from'@health/contracts';import{spacing}from'@health/design-tokens';import{defaultLocale,t}from'@health/i18n';import{categoryAllowsDuty,categoryRequiresSpecialty}from'../features/directory/category-presentation.js';import{useApp}from'../platform/AppContext.js';import{AppButton}from'../ui/AppButton.js';import{AppText}from'../ui/AppText.js';import{EmptyState}from'../ui/EmptyState.js';import{FacilityCard}from'../ui/FacilityCard.js';import{FilterChip}from'../ui/FilterChip.js';import{LoadingState}from'../ui/LoadingState.js';import{Screen}from'../ui/Screen.js';import type{RootStackParamList}from'../navigation/types.js';
export function DirectoryListScreen({route,navigation}:NativeStackScreenProps<RootStackParamList,'Directory'>){const{publicApi,province,coordinates}=useApp();const{categoryId}=route.params;const[category,setCategory]=useState<DirectoryCategoryDTO>();const[specialties,setSpecialties]=useState<Awaited<ReturnType<typeof publicApi.specialties>>>([]);const[selectedSpecialty,setSelectedSpecialty]=useState(route.params.specialtyId);const[openNow,setOpenNow]=useState(false);const[dutyNow,setDutyNow]=useState(false);const[items,setItems]=useState<FacilityListDTO[]>([]);const[page,setPage]=useState(1);const[totalPages,setTotalPages]=useState(0);const[loading,setLoading]=useState(false);const[loadingMore,setLoadingMore]=useState(false);
 useEffect(()=>{if(!province)return;void publicApi.categories(province.id,'public').then(cats=>setCategory(cats.find(x=>x.id===categoryId)))},[province,publicApi,categoryId]);
 useEffect(()=>{if(category&&categoryRequiresSpecialty(category))void publicApi.specialties().then(setSpecialties)},[category,publicApi]);
 const loadPage=useCallback(async(targetPage:number,append:boolean)=>{if(!province||!category||categoryRequiresSpecialty(category)&&!selectedSpecialty){setItems([]);setTotalPages(0);return}append?setLoadingMore(true):setLoading(true);try{const r=await publicApi.facilities({provinceId:province.id,categoryId:category.id,specialtyId:selectedSpecialty,openNow,dutyNow,coordinates,page:targetPage,pageSize:20});setItems(current=>append?[...current,...r.items]:[...r.items]);setPage(targetPage);setTotalPages(r.pagination.totalPages)}finally{append?setLoadingMore(false):setLoading(false)}},[province,category,selectedSpecialty,openNow,dutyNow,coordinates,publicApi]);
 useEffect(()=>{setPage(1);setTotalPages(0);void loadPage(1,false)},[loadPage]);
 if(!category)return <Screen>{loading?<LoadingState/>:<EmptyState message={t(defaultLocale,'common.error')}/>}</Screen>;
 const needsSpecialty=categoryRequiresSpecialty(category),allowsDuty=categoryAllowsDuty(category);return <Screen><ScrollView contentContainerStyle={styles.content}><AppText style={styles.title}>{category.nameAr}</AppText>{needsSpecialty?<><AppText style={styles.label}>{t(defaultLocale,'doctor.chooseSpecialty')}</AppText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{specialties.map(s=><FilterChip key={s.id} label={s.nameAr} selected={selectedSpecialty===s.id} onPress={()=>setSelectedSpecialty(s.id)}/>)}</ScrollView></>:null}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}><FilterChip label={t(defaultLocale,'filter.openNow')} selected={openNow} onPress={()=>setOpenNow(v=>!v)}/>{allowsDuty?<FilterChip label={t(defaultLocale,'filter.dutyNow')} selected={dutyNow} onPress={()=>setDutyNow(v=>!v)}/>:null}</ScrollView>{needsSpecialty&&!selectedSpecialty?<EmptyState message={t(defaultLocale,'doctor.chooseSpecialty')}/>:loading?<LoadingState/>:items.length?items.map(f=><FacilityCard key={f.id} facility={f} onPress={()=>navigation.navigate('FacilityDetail',{facilityId:f.id})}/>):<EmptyState message={dutyNow?t(defaultLocale,'discovery.empty.dutyPharmacies'):t(defaultLocale,'discovery.empty.category')}/>} {!loading&&page<totalPages?<AppButton label={loadingMore?t(defaultLocale,'common.loading'):t(defaultLocale,'action.loadMore')} variant="secondary" onPress={()=>void loadPage(page+1,true)} disabled={loadingMore}/>:null}<AppButton label={t(defaultLocale,'location.change')} variant="ghost" icon="location" onPress={()=>navigation.navigate('ProvincePicker')}/></ScrollView></Screen>}
const styles=StyleSheet.create({content:{gap:spacing.lg,paddingBottom:spacing.xxl},title:{fontSize:25,fontWeight:'800'},label:{fontWeight:'700'},row:{flexDirection:'row-reverse',gap:spacing.sm}});
