import React,{useEffect,useState}from'react';
import{ScrollView,StyleSheet,View}from'react-native';
import type{NativeStackScreenProps}from'@react-navigation/native-stack';
import{DAYS_OF_WEEK,type CoordinatesDTO,type DirectoryCategoryDTO,type FacilityImageDTO,type FacilitySpecialization,type FacilityStatus}from'@health/contracts';
import{LAUNCH_DEFAULT_MAP_CENTER}from'@health/config';import{radius,semanticColors,spacing}from'@health/design-tokens';import{defaultLocale,t}from'@health/i18n';
import{categoryIconKey}from'../features/directory/category-presentation.js';import{FacilityImagesEditor}from'../features/owner/FacilityImagesEditor.js';import{FacilityVerificationEditor}from'../features/owner/FacilityVerificationEditor.js';import{useApp}from'../platform/AppContext.js';import{MapLocationPicker}from'../platform/maps/MapLocationPicker.js';import{AppButton}from'../ui/AppButton.js';import{AppIcon}from'../ui/AppIcon.js';import{AppText}from'../ui/AppText.js';import{AppTextField}from'../ui/AppTextField.js';import{FilterChip}from'../ui/FilterChip.js';import{LoadingState}from'../ui/LoadingState.js';import{Screen}from'../ui/Screen.js';import type{RootStackParamList}from'../navigation/types.js';
type Props=NativeStackScreenProps<RootStackParamList,'JoinFacility'>;
type SelectedCategory=Pick<DirectoryCategoryDTO,'id'|'nameAr'|'iconKey'|'specialization'|'capabilities'>;
export function JoinFacilityScreen({route,navigation}:Props){
 const{ownerApi,publicApi,province,coordinates,useCurrentLocation}=useApp();const[facilityId,setFacilityId]=useState(route.params?.facilityId);const[category,setCategory]=useState<SelectedCategory>();const[specialization,setSpecialization]=useState<FacilitySpecialization>('GENERIC');const[registrationCategories,setRegistrationCategories]=useState<readonly DirectoryCategoryDTO[]>([]);const[status,setStatus]=useState<FacilityStatus>('DRAFT');const[step,setStep]=useState(0);const[loading,setLoading]=useState(Boolean(route.params?.facilityId));
 const[workingProvinceId,setWorkingProvinceId]=useState(province?.id);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[address,setAddress]=useState('');const[description,setDescription]=useState('');const[cities,setCities]=useState<Awaited<ReturnType<typeof publicApi.cities>>>([]);const[cityId,setCityId]=useState('');const[selectedCoordinates,setSelectedCoordinates]=useState<CoordinatesDTO>();
 const[startTime,setStartTime]=useState('08:00');const[endTime,setEndTime]=useState('20:00');const[specialties,setSpecialties]=useState<Awaited<ReturnType<typeof publicApi.specialties>>>([]);const[specialtyId,setSpecialtyId]=useState('');const[doctorName,setDoctorName]=useState('');const[nursingServices,setNursingServices]=useState<Awaited<ReturnType<typeof publicApi.nursingServices>>>([]);const[selectedServices,setSelectedServices]=useState<string[]>([]);const[responsible,setResponsible]=useState('');const[license,setLicense]=useState('');const[images,setImages]=useState<readonly FacilityImageDTO[]>([]);const[verificationComplete,setVerificationComplete]=useState(false);const[message,setMessage]=useState<string>();
 useEffect(()=>{if(!province)return;void publicApi.cities(province.id).then(setCities);void publicApi.categories(province.id,'registration').then(setRegistrationCategories);void publicApi.specialties().then(setSpecialties);void publicApi.nursingServices().then(setNursingServices)},[province,publicApi]);
 useEffect(()=>{if(!route.params?.facilityId)return;ownerApi.detail(route.params.facilityId).then(async d=>{setSpecialization(d.specialization);setStatus(d.status);setCategory({id:d.categoryId,nameAr:d.categoryNameAr,iconKey:d.categoryIconKey,specialization:d.specialization,capabilities:d.categoryCapabilities});setName(d.name??'');setPhone(d.phone??'');setAddress(d.addressText??'');setDescription(d.description??'');setCityId(d.cityId??'');setSelectedCoordinates(d.coordinates);setImages(d.images);if(d.provinceId){setWorkingProvinceId(d.provinceId);setCities(await publicApi.cities(d.provinceId))}if(d.clinicProfile){setDoctorName(d.clinicProfile.doctorName??'');setSpecialtyId(d.clinicProfile.specialtyId??'')}if(d.nursingProfile){setResponsible(d.nursingProfile.responsiblePersonName??'');setSelectedServices([...d.nursingProfile.serviceIds])}if(d.pharmacyProfile)setLicense(d.pharmacyProfile.licenseNumber??'');const first=d.businessHours.find(day=>!day.isClosed&&!day.is24Hours&&day.periods[0]);if(first?.periods[0]){setStartTime(first.periods[0].startTime);setEndTime(first.periods[0].endTime)}setStep(1)}).catch(()=>setMessage(t(defaultLocale,'common.error'))).finally(()=>setLoading(false))},[route.params?.facilityId,ownerApi,publicApi]);
 const create=async(next:DirectoryCategoryDTO)=>{if(!province)return;try{const draft=await ownerApi.createDraft({categoryId:next.id,provinceId:province.id});setWorkingProvinceId(province.id);setFacilityId(draft.id);setCategory(next);setSpecialization(next.specialization as FacilitySpecialization);setStatus('DRAFT');setStep(1)}catch{setMessage(t(defaultLocale,'common.error'))}};
 const saveBasic=async()=>{if(!facilityId||!workingProvinceId||!cityId||!name||!phone||!address)return setMessage(t(defaultLocale,'auth.invalidForm'));try{await ownerApi.basic(facilityId,{name,phone,description:description||undefined,provinceId:workingProvinceId,cityId,addressText:address});setStep(2)}catch{setMessage(t(defaultLocale,'common.error'))}};
 const useGps=async()=>{const loc=await useCurrentLocation();if(loc.mode==='DEVICE_LOCATION'&&loc.deviceLocation)setSelectedCoordinates(loc.deviceLocation.coordinates)};
 const saveLocation=async()=>{if(!facilityId||!workingProvinceId||!cityId||!selectedCoordinates)return setMessage(t(defaultLocale,'auth.invalidForm'));try{await ownerApi.location(facilityId,{coordinates:selectedCoordinates,provinceId:workingProvinceId,cityId,addressText:address});setStep(category?.capabilities.businessHours===true?3:(category?.capabilities.photos===true||specialization!=='GENERIC'?4:5))}catch{setMessage(t(defaultLocale,'common.error'))}};
 const saveHours=async()=>{if(!facilityId||startTime===endTime)return setMessage(t(defaultLocale,'auth.invalidForm'));const endsNextDay=endTime<startTime;try{await ownerApi.hours(facilityId,{days:DAYS_OF_WEEK.map(dayOfWeek=>({dayOfWeek,isClosed:false,is24Hours:false,periods:[{startTime,endTime,endsNextDay}]}))});setStep(category?.capabilities.photos===true||specialization!=='GENERIC'?4:5)}catch{setMessage(t(defaultLocale,'common.error'))}};
 const saveProfile=async()=>{if(!facilityId)return;try{if(specialization==='PHARMACY')await ownerApi.pharmacyProfile(facilityId,{licenseNumber:license||undefined});if(specialization==='MEDICAL_CLINIC'){if(!doctorName||!specialtyId)return setMessage(t(defaultLocale,'auth.invalidForm'));await ownerApi.clinicProfile(facilityId,{doctorName,specialtyId})}if(specialization==='NURSING_CENTER'){if(!selectedServices.length)return setMessage(t(defaultLocale,'auth.invalidForm'));await ownerApi.nursingProfile(facilityId,{responsiblePersonName:responsible||undefined,serviceIds:selectedServices})}setStep(5)}catch{setMessage(t(defaultLocale,'common.error'))}};
 const finish=async()=>{if(!facilityId)return;try{if(status==='DRAFT'||status==='REJECTED'||status==='REVERIFICATION_REQUIRED'){await ownerApi.submit(facilityId);navigation.replace('MyFacilities');return}navigation.replace('ManageFacility',{facilityId})}catch{setMessage(t(defaultLocale,'common.error'))}};
 if(loading)return <Screen><LoadingState/></Screen>;const mapCenter=selectedCoordinates??coordinates??LAUNCH_DEFAULT_MAP_CENTER;
 return <Screen><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><AppText style={styles.title}>{t(defaultLocale,'facility.joinTitle')}</AppText>{category?<AppText style={styles.subtitle}>{category.nameAr}</AppText>:null}<View style={styles.progress}>{[0,1,2,3,4,5,6].map(x=><View key={x} style={[styles.dot,x<=step&&styles.dotActive]}/>)}</View>{message?<AppText style={styles.message}>{message}</AppText>:null}
 {step===0?<View style={styles.types}>{registrationCategories.map(c=><AppButton key={c.id} label={c.nameAr} icon={categoryIconKey(c)} variant="secondary" onPress={()=>void create(c)}/>)}</View>:null}
 {step===1?<><AppTextField label={t(defaultLocale,'facility.name')} value={name} onChangeText={setName}/><AppTextField label={t(defaultLocale,'facility.phone')} value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><AppTextField label={t(defaultLocale,'facility.address')} value={address} onChangeText={setAddress}/><AppTextField label={t(defaultLocale,'facility.description')} value={description} onChangeText={setDescription} multiline/><AppText style={styles.label}>{t(defaultLocale,'facility.city')}</AppText><View style={styles.chips}>{cities.map(c=><FilterChip key={c.id} label={c.nameAr} selected={cityId===c.id} onPress={()=>setCityId(c.id)}/>)}</View><AppButton label={t(defaultLocale,'action.continue')} onPress={()=>void saveBasic()}/></>:null}
 {step===2?<><AppText style={styles.label}>{t(defaultLocale,'facility.pickOnMap')}</AppText><AppText style={styles.hint}>{t(defaultLocale,'facility.mapHint')}</AppText><MapLocationPicker value={selectedCoordinates} center={mapCenter} onChange={setSelectedCoordinates}/><AppButton label={t(defaultLocale,'location.useCurrent')} icon="location" variant="secondary" onPress={()=>void useGps()}/>{selectedCoordinates?<AppText style={styles.selected}>{t(defaultLocale,'facility.locationSelected')}</AppText>:null}<AppButton label={t(defaultLocale,'action.continue')} onPress={()=>void saveLocation()}/></>:null}
 {step===3&&category?.capabilities.businessHours===true?<><AppText style={styles.label}>{t(defaultLocale,'facility.businessHours')}</AppText><AppTextField label={t(defaultLocale,'facility.hoursFrom')} value={startTime} onChangeText={setStartTime}/><AppTextField label={t(defaultLocale,'facility.hoursTo')} value={endTime} onChangeText={setEndTime}/><AppText style={styles.hint}>{t(defaultLocale,'facility.applyAllWeek')}</AppText><AppButton label={t(defaultLocale,'action.continue')} onPress={()=>void saveHours()}/></>:null}
 {step===4&&facilityId?<>{category?.capabilities.photos===true?<FacilityImagesEditor facilityId={facilityId} ownerApi={ownerApi} images={images} onChange={setImages}/>:null}{specialization==='PHARMACY'?<AppTextField label={t(defaultLocale,'facility.licenseNumber')} value={license} onChangeText={setLicense}/>:null}{specialization==='MEDICAL_CLINIC'?<><AppTextField label={t(defaultLocale,'facility.doctorName')} value={doctorName} onChangeText={setDoctorName}/><AppText style={styles.label}>{t(defaultLocale,'doctor.chooseSpecialty')}</AppText><View style={styles.chips}>{specialties.map(s=><FilterChip key={s.id} label={s.nameAr} selected={specialtyId===s.id} onPress={()=>setSpecialtyId(s.id)}/>)}</View></>:null}{specialization==='NURSING_CENTER'?<><AppTextField label={t(defaultLocale,'facility.responsiblePerson')} value={responsible} onChangeText={setResponsible}/><AppText style={styles.label}>{t(defaultLocale,'facility.services')}</AppText><View style={styles.chips}>{nursingServices.map(s=><FilterChip key={s.id} label={s.nameAr} selected={selectedServices.includes(s.id)} onPress={()=>setSelectedServices(current=>current.includes(s.id)?current.filter(x=>x!==s.id):[...current,s.id])}/>)}</View></>:null}<AppButton label={t(defaultLocale,'action.continue')} onPress={()=>void saveProfile()}/></>:null}
 {step===5&&facilityId?<><FacilityVerificationEditor facilityId={facilityId} ownerApi={ownerApi} onCompleteChange={setVerificationComplete}/><AppButton label={t(defaultLocale,'action.continue')} disabled={!verificationComplete} onPress={()=>setStep(6)}/></>:null}
 {step===6?<><AppText style={styles.review}>{t(defaultLocale,'facility.submitHint')}</AppText><View style={styles.summary}><AppIcon name={category?categoryIconKey(category):'store'} size={26}/><View style={styles.grow}><AppText style={styles.summaryName}>{name}</AppText><AppText>{category?.nameAr}</AppText><AppText>{address}</AppText><AppText>{images.length} {t(defaultLocale,'facility.images')}</AppText></View></View><AppButton label={status==='DRAFT'||status==='REJECTED'||status==='REVERIFICATION_REQUIRED'?t(defaultLocale,'action.submit'):t(defaultLocale,'action.save')} onPress={()=>void finish()}/></>:null}
 {step>0&&step<6?<AppButton label={t(defaultLocale,'action.back')} variant="ghost" onPress={()=>setStep(v=>v===5&&category?.capabilities.photos!==true&&specialization==='GENERIC'?(category?.capabilities.businessHours===true?3:2):v===4&&category?.capabilities.businessHours!==true?2:Math.max(0,v-1))}/>:null}</ScrollView></Screen>;
}
const styles=StyleSheet.create({content:{gap:spacing.lg,paddingBottom:spacing.xxl},title:{fontSize:26,fontWeight:'900'},subtitle:{color:semanticColors.primary,fontWeight:'700'},progress:{flexDirection:'row-reverse',gap:spacing.xs},dot:{height:6,flex:1,borderRadius:3,backgroundColor:semanticColors.border},dotActive:{backgroundColor:semanticColors.primary},message:{color:semanticColors.warning},types:{gap:spacing.md},label:{fontWeight:'800'},chips:{flexDirection:'row-reverse',flexWrap:'wrap',gap:spacing.sm},hint:{color:semanticColors.textSecondary,fontSize:13},selected:{color:semanticColors.success,fontWeight:'800'},review:{fontSize:17,fontWeight:'700'},summary:{flexDirection:'row-reverse',gap:spacing.md,padding:spacing.lg,borderRadius:radius.lg,borderWidth:1,borderColor:semanticColors.border,backgroundColor:semanticColors.surface},grow:{flex:1,gap:spacing.xs},summaryName:{fontSize:18,fontWeight:'900'}});
