import React,{useCallback,useEffect,useState}from'react';
import{ScrollView,StyleSheet,View}from'react-native';
import type{NativeStackScreenProps}from'@react-navigation/native-stack';
import type{OwnerFacilityDetailDTO,TemporaryClosureDTO}from'@health/contracts';
import{radius,semanticColors,spacing}from'@health/design-tokens';
import{defaultLocale,t,type TranslationKey}from'@health/i18n';
import{FacilityImagesEditor}from'../features/owner/FacilityImagesEditor.js';
import{categoryIconKey}from'../features/directory/category-presentation.js';
import{useApp}from'../platform/AppContext.js';
import{AppButton}from'../ui/AppButton.js';
import{AppIcon}from'../ui/AppIcon.js';
import{AppText}from'../ui/AppText.js';
import{AppTextField}from'../ui/AppTextField.js';
import{LoadingState}from'../ui/LoadingState.js';
import{Screen}from'../ui/Screen.js';
import{SectionTitle}from'../ui/SectionTitle.js';
import type{RootStackParamList}from'../navigation/types.js';

const statusKey:Record<OwnerFacilityDetailDTO['status'],TranslationKey>={DRAFT:'status.draft',PENDING_REVIEW:'status.pending',ACTIVE:'status.active',REJECTED:'status.rejected',REVERIFICATION_REQUIRED:'status.reverification',SUSPENDED:'status.suspended',CLOSED:'status.closed'};
export function ManageFacilityScreen({route,navigation}:NativeStackScreenProps<RootStackParamList,'ManageFacility'>){
 const{ownerApi}=useApp();const[data,setData]=useState<OwnerFacilityDetailDTO>();const[closure,setClosure]=useState<TemporaryClosureDTO|null>();const[hours,setHours]=useState('4');const[message,setMessage]=useState<string>();
 const load=useCallback(async()=>{const [detail,active]=await Promise.all([ownerApi.detail(route.params.facilityId),ownerApi.activeClosure(route.params.facilityId)]);setData(detail);setClosure(active)},[ownerApi,route.params.facilityId]);useEffect(()=>{void load().catch(()=>setMessage(t(defaultLocale,'common.error')))},[load]);
 const close=async()=>{const duration=Number(hours);if(!Number.isFinite(duration)||duration<=0||duration>168)return setMessage(t(defaultLocale,'auth.invalidForm'));const startsAt=new Date();const endsAt=new Date(startsAt.getTime()+duration*3600_000);try{const next=await ownerApi.createClosure(route.params.facilityId,{startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString()});setClosure(next);setMessage(t(defaultLocale,'common.saved'))}catch{setMessage(t(defaultLocale,'common.error'))}};
 const reopen=async()=>{if(!closure)return;try{await ownerApi.cancelClosure(route.params.facilityId,closure.id);setClosure(null);setMessage(t(defaultLocale,'common.saved'))}catch{setMessage(t(defaultLocale,'common.error'))}};
 const requestReverification=async()=>{try{await ownerApi.requestReverification(route.params.facilityId);navigation.replace('JoinFacility',{facilityId:route.params.facilityId})}catch{setMessage(t(defaultLocale,'common.error'))}};
 if(!data)return <Screen><LoadingState/></Screen>;
 return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><AppIcon name={categoryIconKey({iconKey:data.categoryIconKey})} size={36} color={semanticColors.primary}/><View style={styles.grow}><AppText style={styles.title}>{data.name??t(defaultLocale,'facility.manage')}</AppText><AppText style={styles.status}>{t(defaultLocale,statusKey[data.status])}</AppText></View></View>{message?<AppText style={styles.message}>{message}</AppText>:null}{data.status==='ACTIVE'?<><AppText style={styles.muted}>{t(defaultLocale,'facility.reverificationHint')}</AppText><AppButton label={t(defaultLocale,'facility.requestReverification')} icon="edit" onPress={()=>void requestReverification()}/></>:data.status==='SUSPENDED'?<AppText style={styles.muted}>{t(defaultLocale,'facility.suspendedAdminOnly')}</AppText>:data.status==='REVERIFICATION_REQUIRED'?<AppButton label={t(defaultLocale,'facility.manageInfo')} icon="edit" onPress={()=>navigation.navigate('JoinFacility',{facilityId:data.id})}/>:null}{data.categoryCapabilities.duty===true&&data.status==='ACTIVE'?<AppButton label={t(defaultLocale,'duty.title')} icon="duty" variant="secondary" onPress={()=>navigation.navigate('Duty',{facilityId:data.id,facilityName:data.name})}/>:null}{data.categoryCapabilities.photos===true?<><SectionTitle title={t(defaultLocale,'facility.images')}/><FacilityImagesEditor facilityId={data.id} ownerApi={ownerApi} images={data.images} onChange={images=>setData(current=>current?{...current,images}:current)}/></>:null}<SectionTitle title={t(defaultLocale,'facility.temporaryClosure')}/>{closure?<View style={styles.closure}><AppIcon name="warning" color={semanticColors.warning}/><View style={styles.grow}><AppText style={styles.closureTitle}>{t(defaultLocale,'facility.closedUntil')}</AppText><AppText>{new Date(closure.endsAt).toLocaleString()}</AppText></View><AppButton label={t(defaultLocale,'facility.reopenNow')} variant="ghost" onPress={()=>void reopen()}/></View>:data.status==='ACTIVE'?<><AppTextField label={t(defaultLocale,'facility.closeForHours')} value={hours} onChangeText={setHours} keyboardType="number-pad"/><AppButton label={t(defaultLocale,'facility.temporaryClosure')} icon="close" variant="secondary" onPress={()=>void close()}/></>:<AppText style={styles.muted}>{t(defaultLocale,'facility.noActiveClosure')}</AppText>}<SectionTitle title={t(defaultLocale,'facility.location')}/><AppText>{data.addressText??'—'}</AppText>{data.categoryCapabilities.businessHours===true?<><SectionTitle title={t(defaultLocale,'facility.businessHours')}/>{data.businessHours.map(day=><View key={day.dayOfWeek} style={styles.day}><AppText style={styles.dayName}>{t(defaultLocale,`day.${day.dayOfWeek}` as TranslationKey)}</AppText><AppText>{day.isClosed?t(defaultLocale,'status.closedNow'):day.is24Hours?'24/7':day.periods.map(p=>`${p.startTime}–${p.endTime}`).join('، ')}</AppText></View>)}</>:null}</ScrollView></Screen>;
}
const styles=StyleSheet.create({content:{gap:spacing.lg,paddingBottom:spacing.xxl},hero:{flexDirection:'row-reverse',gap:spacing.md,alignItems:'center',padding:spacing.lg,borderRadius:radius.lg,borderWidth:1,borderColor:semanticColors.border,backgroundColor:semanticColors.surface},grow:{flex:1},title:{fontSize:22,fontWeight:'900'},status:{color:semanticColors.primary,fontWeight:'700'},message:{color:semanticColors.warning},closure:{flexDirection:'row-reverse',alignItems:'center',gap:spacing.md,padding:spacing.md,borderWidth:1,borderColor:semanticColors.warning,borderRadius:radius.md,backgroundColor:semanticColors.surface},closureTitle:{fontWeight:'800'},muted:{color:semanticColors.textSecondary},day:{flexDirection:'row-reverse',justifyContent:'space-between',gap:spacing.md},dayName:{fontWeight:'800'}});
