import React,{useCallback,useEffect,useState}from'react';
import{StyleSheet,View}from'react-native';
import{launchImageLibrary}from'react-native-image-picker';
import{radius,semanticColors,spacing}from'@health/design-tokens';
import{defaultLocale,t}from'@health/i18n';
import type{OwnerApi}from'../../api/owner-api.js';
import{AppButton}from'../../ui/AppButton.js';import{AppIcon}from'../../ui/AppIcon.js';import{AppText}from'../../ui/AppText.js';import{LoadingState}from'../../ui/LoadingState.js';
interface Evidence{readonly id:string;readonly mimeType:string;readonly sizeBytes:number;readonly createdAt:string}
interface Requirement{readonly id:string;readonly code:string;readonly labelAr:string;readonly instructionsAr?:string;readonly isRequired:boolean;readonly minFiles:number;readonly maxFiles:number;readonly uploadedCount:number;readonly complete:boolean;readonly evidence:readonly Evidence[]}
interface Summary{readonly complete:boolean;readonly requirements:readonly Requirement[]}
export function FacilityVerificationEditor({facilityId,ownerApi,onCompleteChange}:{facilityId:string;ownerApi:OwnerApi;onCompleteChange?:(complete:boolean)=>void}){
 const[data,setData]=useState<Summary>();const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string>();
 const load=useCallback(async()=>{const next=await ownerApi.verification(facilityId) as Summary;setData(next);onCompleteChange?.(next.complete)},[facilityId,ownerApi,onCompleteChange]);useEffect(()=>{void load()},[load]);
 const upload=async(requirementId:string)=>{const result=await launchImageLibrary({mediaType:'photo',selectionLimit:1,quality:.85});const asset=result.assets?.[0];if(!asset?.uri)return;setBusy(true);setMessage(undefined);try{await ownerApi.uploadVerification(facilityId,requirementId,{uri:asset.uri,type:asset.type??'image/jpeg',name:asset.fileName??'verification.jpg'});await load()}catch{setMessage(t(defaultLocale,'verification.uploadFailed'))}finally{setBusy(false)}};
 const remove=async(evidenceId:string)=>{setBusy(true);try{await ownerApi.deleteVerification(facilityId,evidenceId);await load()}finally{setBusy(false)}};
 if(!data)return <LoadingState/>;return <View style={styles.wrap}><View style={styles.notice}><AppIcon name="lock" color={semanticColors.primary}/><View style={styles.grow}><AppText style={styles.title}>{t(defaultLocale,'verification.title')}</AppText><AppText style={styles.hint}>{t(defaultLocale,'verification.privateHint')}</AppText></View></View>{message?<AppText style={styles.error}>{message}</AppText>:null}{data.requirements.map(req=><View key={req.id} style={styles.card}><View style={styles.row}><AppIcon name={req.complete?'approve':'image'} color={req.complete?semanticColors.success:semanticColors.textSecondary}/><View style={styles.grow}><AppText style={styles.req}>{req.labelAr}{req.isRequired?` · ${t(defaultLocale,'verification.required')}`:''}</AppText>{req.instructionsAr?<AppText style={styles.hint}>{req.instructionsAr}</AppText>:null}<AppText style={styles.hint}>{req.uploadedCount}/{req.minFiles}</AppText></View></View>{req.evidence.map(e=><View key={e.id} style={styles.evidence}><AppText>{t(defaultLocale,'verification.uploaded')}</AppText><AppButton label={t(defaultLocale,'action.delete')} icon="delete" variant="ghost" disabled={busy} onPress={()=>void remove(e.id)}/></View>)}{req.uploadedCount<req.maxFiles?<AppButton label={t(defaultLocale,'verification.addProof')} icon="image" variant="secondary" disabled={busy} onPress={()=>void upload(req.id)}/>:null}</View>)}</View>
}
const styles=StyleSheet.create({wrap:{gap:spacing.md},notice:{flexDirection:'row-reverse',gap:spacing.md,padding:spacing.md,borderRadius:radius.md,backgroundColor:semanticColors.primarySoft},grow:{flex:1,gap:spacing.xs},title:{fontWeight:'900',fontSize:18},hint:{color:semanticColors.textSecondary,fontSize:13},error:{color:semanticColors.danger},card:{gap:spacing.sm,padding:spacing.md,borderRadius:radius.lg,borderWidth:1,borderColor:semanticColors.border,backgroundColor:semanticColors.surface},row:{flexDirection:'row-reverse',gap:spacing.sm},req:{fontWeight:'800'},evidence:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',gap:spacing.sm}});
