import{existsSync,readFileSync}from'node:fs';const read=p=>readFileSync(p,'utf8');const checks=[];const check=(name,ok)=>{checks.push([name,!!ok]);console.log(`${ok?'PASS':'FAIL'} - ${name}`)};
check('Production compose exists',existsSync('infrastructure/production/docker-compose.yml'));
const compose=read('infrastructure/production/docker-compose.yml');
check('Production compose has fixed project name',compose.includes('name: health-directory'));
const postgresBlock=compose.split('  postgres:')[1]?.split('\n  api:')[0]??'';check('PostgreSQL is internal-only',compose.includes('internal: true')&&!postgresBlock.includes('ports:'));
check('API/admin/caddy services configured',['api:','admin:','caddy:','postgres:'].every(x=>compose.includes(x)));
check('Persistent DB and upload volumes',compose.includes('postgres_data:')&&compose.includes('upload_data:'));
const restore=read('infrastructure/production/restore.sh');
check('Production restore covers DB and upload volume',restore.includes('pg_restore')&&restore.includes('health-directory_upload_data')&&restore.includes('CONFIRM_PRODUCTION_RESTORE=RESTORE')&&restore.includes('backup.sh'));
check('HTTPS reverse proxy configured',read('infrastructure/production/Caddyfile').includes('Strict-Transport-Security'));
check('Tracked migration runner exists',read('scripts/db-migrate.mjs').includes('schema_migrations'));
check('Initial admin command has no default password',read('apps/api/src/cli/create-admin.ts').includes('ADMIN_PASSWORD')&&!read('apps/api/src/cli/create-admin.ts').includes("ADMIN_PASSWORD='"));
check('Production preflight exists',existsSync('scripts/production-preflight.mjs'));
check('Production smoke test documented',existsSync('docs/operations/production-smoke-test.md'));
check('Release manifest remains not released',read('docs/releases/v1.0.0.md').includes('NOT RELEASED'));
check('Release manifest declares pharmacy-only initial scope',read('docs/releases/v1.0.0.md').includes('Pharmacy directory + Pharmacy Duty'));
const evidencePurge=read('apps/api/src/cli/purge-verification-evidence.ts');const evidenceRetention=read('docs/security/verification-evidence-retention.md');
check('Verification evidence retention is configurable and purgeable',evidencePurge.includes('VERIFICATION_EVIDENCE_PURGE_EXECUTE')&&evidencePurge.includes('REJECTED')&&evidencePurge.includes('CLOSED')&&evidenceRetention.includes('90 days'));
check('Production smoke test validates dynamic activation',read('docs/operations/production-smoke-test.md').includes('temporary generic test category'));
const failed=checks.filter(([,ok])=>!ok);if(failed.length){console.error(`Phase 15 preparation: ${checks.length-failed.length}/${checks.length} PASS`);process.exit(1)}console.log(`Phase 15 preparation: ${checks.length}/${checks.length} PASS`);
