import { existsSync, readFileSync } from 'node:fs';
const root=new URL('../',import.meta.url);const path=(p)=>new URL(p,root);const read=(p)=>readFileSync(path(p),'utf8');
const checks=[];const check=(name,ok)=>{checks.push([name,Boolean(ok)]);console.log(`${ok?'PASS':'FAIL'} - ${name}`)};
const screens=['HomeScreen','DirectoryListScreen','SearchScreen','MapScreen','FacilityDetailScreen','LoginScreen','RegisterScreen','RecoveryScreen','AccountScreen','MyRatingsScreen','MyFacilitiesScreen','JoinFacilityScreen','ManageFacilityScreen','DutyScreen','ProvincePickerScreen'];
check('Android core screens exist',screens.every(x=>existsSync(path(`apps/mobile/src/screens/${x}.tsx`))));
const nav=read('apps/mobile/src/navigation/RootNavigation.tsx');
check('Owner management route wired',nav.includes('ManageFacilityScreen')&&nav.includes('name="ManageFacility"'));
const join=read('apps/mobile/src/screens/JoinFacilityScreen.tsx');
check('Facility join uses map location picker',join.includes('MapLocationPicker')&&!join.includes('facility.latitude'));
check('Facility join manages facility images',join.includes('FacilityImagesEditor'));
const imageController=read('apps/api/src/modules/facilities/facility-image.controller.ts');
check('Facility images API supports upload/delete/primary/order',imageController.includes("@Post()")&&imageController.includes("@Delete(':imageId')")&&imageController.includes("@Post(':imageId/primary')")&&imageController.includes("@Patch('order')"));
const manage=read('apps/mobile/src/screens/ManageFacilityScreen.tsx');
check('Owner management covers edit/images/temporary closure/duty',manage.includes('FacilityImagesEditor')&&manage.includes('createClosure')&&manage.includes("navigation.navigate('JoinFacility'")&&manage.includes("navigation.navigate('Duty'"));
const availability=read('apps/api/src/modules/availability/availability.controller.ts');
check('Temporary closure active state is queryable',availability.includes("@Get('active')"));
const detail=read('apps/mobile/src/screens/FacilityDetailScreen.tsx');
check('Public actions use centralized services',detail.includes('directionsService.open')&&detail.includes('phoneActionService.dial')&&!detail.includes('Linking'));
const publicDiscovery=read('apps/api/src/modules/discovery/public-discovery.service.ts');
check('Public facility media returns API media URLs',publicDiscovery.includes("'/api/v1/media/' || storage_key"));
const admin=read('apps/admin/src/components/AdminConsole.tsx');
check('Light admin supports applications/facilities/references/settings',admin.includes('applications')&&admin.includes('facilities')&&admin.includes('references')&&admin.includes('settings'));
const dynamicGate=read('scripts/verify-dynamic-directory.mjs');
check('Dynamic directory regression gate is present',dynamicGate.includes('Dynamic directory gate')&&dynamicGate.includes('groupedCategories'));
check('Admin supports category groups and private verification policies',admin.includes('GroupEditor')&&admin.includes('RequirementCard')&&admin.includes('publicVisibility')&&admin.includes('ownerRegistration'));
const centralization=read('scripts/centralization-audit.mjs');
check('Centralization gate remains present',centralization.length>100);
const failed=checks.filter(([,ok])=>!ok);if(failed.length){console.error(`Phase 14 source gate: ${checks.length-failed.length}/${checks.length} PASS`);process.exit(1)}console.log(`Phase 14 source gate: ${checks.length}/${checks.length} PASS`);
