import { Injectable } from '@nestjs/common';
import { PLATFORM_SETTING_DEFINITIONS,isPlatformSettingKey,validatePlatformSettingValue,type PlatformSettingKey } from '@health/config';
import { DatabaseService } from '../../database/database.service.js';
import { FacilityDomainError } from '../facilities/facility-domain.error.js';
@Injectable()export class PlatformSettingsService{private readonly cache=new Map<string,{value:unknown;expiresAt:number}>();private readonly ttlMs=30_000;constructor(private readonly db:DatabaseService){}
 async get<K extends PlatformSettingKey>(key:K):Promise<(typeof PLATFORM_SETTING_DEFINITIONS)[K]['defaultValue']>{const cached=this.cache.get(key);if(cached&&cached.expiresAt>Date.now())return cached.value as any;const r=await this.db.query<{value:unknown}>(`SELECT value_json AS value FROM platform_settings WHERE key=$1`,[key]);const value=r.rows[0]?.value??PLATFORM_SETTING_DEFINITIONS[key].defaultValue;this.cache.set(key,{value,expiresAt:Date.now()+this.ttlMs});return value as any}
 async set(adminUserId:string,key:string,value:unknown){if(!isPlatformSettingKey(key))throw new FacilityDomainError('VALIDATION_ERROR','Unknown platform setting.');if(!validatePlatformSettingValue(key,value))throw new FacilityDomainError('VALIDATION_ERROR','Invalid platform setting value.');if(key==='defaultSearchRadiusMeters'||key==='maxSearchRadiusMeters'){const currentDefault=key==='defaultSearchRadiusMeters'?value:await this.get('defaultSearchRadiusMeters');const currentMax=key==='maxSearchRadiusMeters'?value:await this.get('maxSearchRadiusMeters');if(typeof currentDefault!=='number'||typeof currentMax!=='number'||currentDefault>currentMax)throw new FacilityDomainError('VALIDATION_ERROR','Default search radius cannot exceed maximum search radius.');}const type=PLATFORM_SETTING_DEFINITIONS[key].type;await this.db.query(`INSERT INTO platform_settings(key,value_json,value_type,updated_by) VALUES($1,$2::jsonb,$3,$4) ON CONFLICT(key) DO UPDATE SET value_json=EXCLUDED.value_json,value_type=EXCLUDED.value_type,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[key,JSON.stringify(value),type,adminUserId]);this.cache.set(key,{value,expiresAt:Date.now()+this.ttlMs});return{key,value}}
 async all(){const r=await this.db.query<{key:string;value:unknown;updatedAt:string}>(`SELECT key,value_json AS value,updated_at AS "updatedAt" FROM platform_settings ORDER BY key`);const by=new Map(r.rows.map(x=>[x.key,x]));return Object.entries(PLATFORM_SETTING_DEFINITIONS).map(([key,def])=>({key,value:by.get(key)?.value??def.defaultValue,type:def.type,public:def.public,updatedAt:by.get(key)?.updatedAt}))}
 async publicConfig(){const all=await this.all();return Object.fromEntries(all.filter(x=>x.public).map(x=>[x.key,x.value]))}
}
